<Project>
    <PropertyGroup>
        <BaseTargetFramework>net10.0</BaseTargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <Authors>aritchie;ShinyLib</Authors>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/shinyorg/obd</PackageProjectUrl>
        <RepositoryUrl>https://github.com/shinyorg/obd</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <MauiVersion>10.0.51</MauiVersion>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageReleaseNotes>https://shinylib.net/client/obd/release-notes</PackageReleaseNotes>
        <PackageProjectUrl>https://shinylib.net</PackageProjectUrl>
        <PackageTags>obd obd2 elm327 obdlink vehicle diagnostics shiny bluetooth ble</PackageTags>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <IncludeSource>True</IncludeSource>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>True</PublishRepositoryUrl>
        <EmbedUntrackedSources>True</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)nuget.png" Pack="true" PackagePath="icon.png"/>
        <None Include="$(MSBuildThisFileDirectory)nuget.txt" Pack="true" PackagePath="readme.txt"/>
        <None Include="$(MSBuildThisFileDirectory)readme.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
