<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-android</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);$(BaseTargetFramework)-ios</TargetFrameworks>
        <RootNamespace>Shiny.Obd.Ble</RootNamespace>
        <Description>BLE transport for Shiny.Obd using Shiny.BluetoothLE</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Obd\Shiny.Obd.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Shiny.Obd.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all"/>
        <PackageReference Include="Shiny.BluetoothLE"/>
    </ItemGroup>
</Project>
