<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Obd\Shiny.Obd.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Obd.Ble\Shiny.Obd.Ble.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Obd.Serial\Shiny.Obd.Serial.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Obd.Wifi\Shiny.Obd.Wifi.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Obd.Emulator\Shiny.Obd.Emulator.csproj"/>
    </ItemGroup>

</Project>